version: "3.3"

services:
  db:
    container_name: express-rest-db
    restart: always
    image: express-rest-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - "5432:5432"
  api:
    container_name: express-rest
    restart: always
    image: express-rest
    build:
      context: .
    env_file:
      - ./.env
    # Essential for nodemon restart working
    volumes:
      - ./:/usr/src/app
    networks:
      - network
    depends_on:
      - db
    ports:
      - "8080:8080"

networks:
  network:

volumes:
  db:
